"""initial_schema

Revision ID: cdc82f5bf321
Revises: 
Create Date: 2026-07-13 12:45:59.863466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cdc82f5bf321'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('approvals', 'instance_id',
               existing_type=mysql.INTEGER(),
               comment='所属流程实例',
               existing_comment='鎵?睘娴佺▼瀹炰緥',
               existing_nullable=False)
    op.alter_column('approvals', 'node_id',
               existing_type=mysql.INTEGER(),
               comment='所属节点',
               existing_comment='鎵?睘鑺傜偣',
               existing_nullable=False)
    op.alter_column('approvals', 'task_id',
               existing_type=mysql.INTEGER(),
               comment='关联Task（结束节点为NULL）',
               existing_comment='鍏宠仈鐨凾ask锛堢粨鏉熻妭鐐逛负NULL锛',
               existing_nullable=True)
    op.alter_column('approvals', 'approver_id',
               existing_type=mysql.INTEGER(),
               comment='审批人',
               existing_comment='瀹℃壒浜',
               existing_nullable=False)
    op.alter_column('approvals', 'status',
               existing_type=mysql.ENUM('pending', 'approved', 'rejected', 'terminated', collation='utf8mb4_unicode_ci'),
               nullable=False,
               comment='审批状态',
               existing_comment='瀹℃壒鐘舵?',
               existing_server_default=sa.text("'pending'"))
    op.alter_column('approvals', 'opinion',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='审批意见',
               existing_comment='瀹℃壒鎰忚?',
               existing_nullable=True)
    op.alter_column('approvals', 'reject_target_node_id',
               existing_type=mysql.INTEGER(),
               comment='仅结束节点终审总驳回目标',
               existing_comment='浠呯粨鏉熻妭鐐圭粓瀹℃?椹冲洖鐩?爣锛涗腑闂村?鎵逛负NULL',
               existing_nullable=True)
    op.alter_column('approvals', 'signature_applied',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment='签名是否已上PDF',
               existing_comment='绛惧悕鏄?惁宸蹭笂PDF',
               existing_server_default=sa.text("'0'"))
    op.alter_column('approvals', 'decided_at',
               existing_type=mysql.DATETIME(),
               comment='审批决定时间',
               existing_comment='瀹℃壒鍐冲畾鏃堕棿',
               existing_nullable=True)
    op.alter_column('approvals', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('approvals', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index('idx_approver', table_name='approvals')
    op.drop_index('idx_approver_status', table_name='approvals')
    op.drop_index('idx_instance', table_name='approvals')
    op.drop_index('idx_node', table_name='approvals')
    op.drop_index('idx_task', table_name='approvals')
    op.drop_table_comment(
        'approvals',
        existing_comment='瀹℃壒璁板綍',
        schema=None
    )
    op.alter_column('check_records', 'instance_id',
               existing_type=mysql.INTEGER(),
               comment='所属流程实例',
               existing_comment='鎵?睘娴佺▼瀹炰緥',
               existing_nullable=False)
    op.alter_column('check_records', 'node_id',
               existing_type=mysql.INTEGER(),
               comment='所属节点',
               existing_comment='鎵?睘鑺傜偣',
               existing_nullable=False)
    op.alter_column('check_records', 'task_id',
               existing_type=mysql.INTEGER(),
               comment='关联Task',
               existing_comment='鍏宠仈鐨凾ask',
               existing_nullable=False)
    op.alter_column('check_records', 'checker_id',
               existing_type=mysql.INTEGER(),
               comment='校验人',
               existing_comment='鏍￠獙浜',
               existing_nullable=False)
    op.alter_column('check_records', 'status',
               existing_type=mysql.ENUM('pending', 'passed', 'returned', 'terminated', collation='utf8mb4_unicode_ci'),
               nullable=False,
               comment='校验状态',
               existing_comment='鏍￠獙鐘舵?',
               existing_server_default=sa.text("'pending'"))
    op.alter_column('check_records', 'opinion',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='校验意见',
               existing_comment='鏍￠獙鎰忚?',
               existing_nullable=True)
    op.alter_column('check_records', 'decided_at',
               existing_type=mysql.DATETIME(),
               comment='校验决定时间',
               existing_comment='鏍￠獙鍐冲畾鏃堕棿',
               existing_nullable=True)
    op.alter_column('check_records', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('check_records', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index('idx_checker', table_name='check_records')
    op.drop_index('idx_checker_status', table_name='check_records')
    op.drop_index('idx_instance', table_name='check_records')
    op.drop_index('idx_node', table_name='check_records')
    op.drop_index('idx_task', table_name='check_records')
    op.drop_table_comment(
        'check_records',
        existing_comment='鏍￠獙璁板綍',
        schema=None
    )
    op.alter_column('files', 'instance_id',
               existing_type=mysql.INTEGER(),
               comment='所属流程实例',
               existing_comment='鎵?睘娴佺▼瀹炰緥',
               existing_nullable=False)
    op.alter_column('files', 'node_id',
               existing_type=mysql.INTEGER(),
               comment='上传节点',
               existing_comment='涓婁紶鑺傜偣',
               existing_nullable=True)
    op.alter_column('files', 'task_id',
               existing_type=mysql.INTEGER(),
               comment='关联任务（补交可为NULL）',
               existing_comment='鍏宠仈浠诲姟锛堣ˉ浜ゅ彲涓篘ULL锛',
               existing_nullable=True)
    op.alter_column('files', 'round',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='文件所属轮次',
               existing_comment='鏂囦欢鎵?睘杞??',
               existing_server_default=sa.text("'1'"))
    op.alter_column('files', 'uploader_id',
               existing_type=mysql.INTEGER(),
               comment='上传人',
               existing_comment='涓婁紶浜',
               existing_nullable=False)
    op.alter_column('files', 'upload_type',
               existing_type=mysql.ENUM('normal', 'supplement', collation='utf8mb4_unicode_ci'),
               nullable=False,
               comment='上传类型',
               existing_comment='涓婁紶绫诲瀷',
               existing_server_default=sa.text("'normal'"))
    op.alter_column('files', 'original_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='原始文件名',
               existing_comment='鍘熷?鏂囦欢鍚',
               existing_nullable=False)
    op.alter_column('files', 'stored_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='存储文件名（UUID）',
               existing_comment='瀛樺偍鏂囦欢鍚嶏紙UUID锛',
               existing_nullable=False)
    op.alter_column('files', 'file_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='最终PDF存储相对路径',
               existing_comment='鏈?粓PDF瀛樺偍鐩稿?璺?緞',
               existing_nullable=False)
    op.alter_column('files', 'file_size',
               existing_type=mysql.BIGINT(),
               comment='最终PDF大小（字节）',
               existing_comment='鏈?粓PDF澶у皬锛堝瓧鑺傦級',
               existing_nullable=True)
    op.alter_column('files', 'mime_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='最终文件MIME类型',
               existing_comment='鏈?粓鏂囦欢MIME绫诲瀷',
               existing_nullable=False,
               existing_server_default=sa.text("'application/pdf'"))
    op.alter_column('files', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment='创建时间',
               existing_comment='鍒涘缓鏃堕棿',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('files', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment='更新时间',
               existing_comment='鏇存柊鏃堕棿',
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index('idx_instance', table_name='files')
    op.drop_index('idx_node', table_name='files')
    op.drop_index('idx_task', table_name='files')
    op.drop_index('idx_uploader', table_name='files')
    op.drop_table_comment(
        'files',
        existing_comment='鏂囦欢',
        schema=None
    )
    op.alter_column('flow_instances', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='流程实例名称',
               existing_comment='娴佺▼瀹炰緥鍚嶇О',
               existing_nullable=False)
    op.alter_column('flow_instances', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='补充说明',
               existing_comment='琛ュ厖璇存槑',
               existing_nullable=True)
    op.alter_column('flow_instances', 'template_id',
               existing_type=mysql.INTEGER(),
               comment='使用的模板',
               existing_comment='浣跨敤鐨勬ā鏉',
               existing_nullable=False)
    op.alter_column('flow_instances', 'version_id',
               existing_type=mysql.INTEGER(),
               comment='基于的版本',
               existing_comment='鍩轰簬鐨勭増鏈',
               existing_nullable=False)
    op.alter_column('flow_instances', 'organization_id',
               existing_type=mysql.INTEGER(),
               comment='所属组织',
               existing_comment='鎵?睘缁勭粐',
               existing_nullable=False)
    op.alter_column('flow_instances', 'initiator_id',
               existing_type=mysql.INTEGER(),
               comment='发起人',
               existing_comment='鍙戣捣浜猴紙鎵?暱锛',
               existing_nullable=False)
    op.alter_column('flow_instances', 'priority',
               existing_type=mysql.ENUM('urgent', 'high', 'normal', 'low', collation='utf8mb4_unicode_ci'),
               nullable=False,
               comment='优先级',
               existing_comment='浼樺厛绾',
               existing_server_default=sa.text("'normal'"))
    op.alter_column('flow_instances', 'status',
               existing_type=mysql.ENUM('created', 'running', 'completed', 'terminated', collation='utf8mb4_unicode_ci'),
               nullable=False,
               comment='主状态',
               existing_comment='涓荤姸鎬',
               existing_server_default=sa.text("'created'"))
    op.alter_column('flow_instances', 'archive_status',
               existing_type=mysql.ENUM('not_archived', 'archived', collation='utf8mb4_unicode_ci'),
               nullable=False,
               comment='归档状态',
               existing_comment='褰掓。鐘舵?',
               existing_server_default=sa.text("'not_archived'"))
    op.alter_column('flow_instances', 'termination_reason',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='终止原因',
               existing_comment='缁堟?鍘熷洜',
               existing_nullable=True)
    op.alter_column('flow_instances', 'initiated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment='发起时间',
               existing_comment='鍙戣捣鏃堕棿',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('flow_instances', 'completed_at',
               existing_type=mysql.DATETIME(),
               comment='完成时间',
               existing_comment='瀹屾垚鏃堕棿',
               existing_nullable=True)
    op.alter_column('flow_instances', 'archived_at',
               existing_type=mysql.DATETIME(),
               comment='归档时间',
               existing_comment='褰掓。鏃堕棿',
               existing_nullable=True)
    op.alter_column('flow_instances', 'terminated_at',
               existing_type=mysql.DATETIME(),
               comment='终止时间',
               existing_comment='缁堟?鏃堕棿',
               existing_nullable=True)
    op.alter_column('flow_instances', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('flow_instances', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index('idx_initiator', table_name='flow_instances')
    op.drop_index('idx_initiator_status', table_name='flow_instances')
    op.drop_index('idx_org', table_name='flow_instances')
    op.drop_index('idx_template', table_name='flow_instances')
    op.drop_index('idx_version', table_name='flow_instances')
    op.drop_table_comment(
        'flow_instances',
        existing_comment='娴佺▼瀹炰緥',
        schema=None
    )
    op.alter_column('flow_templates', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='流程名称',
               existing_comment='娴佺▼鍚嶇О',
               existing_nullable=False)
    op.alter_column('flow_templates', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='流程描述',
               existing_comment='娴佺▼鎻忚堪',
               existing_nullable=True)
    op.alter_column('flow_templates', 'organization_id',
               existing_type=mysql.INTEGER(),
               comment='所属组织',
               existing_comment='鎵?睘缁勭粐',
               existing_nullable=False)
    op.alter_column('flow_templates', 'status',
               existing_type=mysql.ENUM('draft', 'published', 'disabled', collation='utf8mb4_unicode_ci'),
               nullable=False,
               comment='模板状态',
               existing_comment='妯℃澘鐘舵?',
               existing_server_default=sa.text("'draft'"))
    op.alter_column('flow_templates', 'current_version',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='当前最新版本号',
               existing_comment='褰撳墠鏈?柊鐗堟湰鍙',
               existing_server_default=sa.text("'0'"))
    op.alter_column('flow_templates', 'created_by',
               existing_type=mysql.INTEGER(),
               comment='创建人',
               existing_comment='鍒涘缓浜',
               existing_nullable=False)
    op.alter_column('flow_templates', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('flow_templates', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index('idx_org', table_name='flow_templates')
    op.drop_index('idx_org_status', table_name='flow_templates')
    op.drop_index('uk_org_name', table_name='flow_templates')
    op.drop_table_comment(
        'flow_templates',
        existing_comment='娴佺▼妯℃澘',
        schema=None
    )
    op.alter_column('flow_versions', 'template_id',
               existing_type=mysql.INTEGER(),
               comment='所属模板',
               existing_comment='鎵?睘妯℃澘',
               existing_nullable=False)
    op.alter_column('flow_versions', 'version_number',
               existing_type=mysql.INTEGER(),
               comment='版本号',
               existing_comment='鐗堟湰鍙',
               existing_nullable=False)
    op.alter_column('flow_versions', 'status',
               existing_type=mysql.ENUM('published', 'disabled', collation='utf8mb4_unicode_ci'),
               nullable=False,
               comment='版本状态',
               existing_comment='鐗堟湰鐘舵?',
               existing_server_default=sa.text("'published'"))
    op.alter_column('flow_versions', 'nodes_snapshot',
               existing_type=mysql.JSON(),
               comment='节点快照',
               existing_comment='鑺傜偣蹇?収',
               existing_nullable=False)
    op.alter_column('flow_versions', 'edges_snapshot',
               existing_type=mysql.JSON(),
               comment='连线快照',
               existing_comment='杩炵嚎蹇?収',
               existing_nullable=False)
    op.alter_column('flow_versions', 'published_by',
               existing_type=mysql.INTEGER(),
               comment='发布人',
               existing_comment='鍙戝竷浜',
               existing_nullable=False)
    op.alter_column('flow_versions', 'published_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment='发布时间',
               existing_comment='鍙戝竷鏃堕棿',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('flow_versions', 'soft_config_overrides',
               existing_type=mysql.JSON(),
               comment='版本级节点软配置覆盖层',
               existing_comment='鐗堟湰绾ц妭鐐硅蒋閰嶇疆瑕嗙洊灞',
               existing_nullable=True)
    op.alter_column('flow_versions', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_template', table_name='flow_versions')
    op.drop_index('uk_template_version', table_name='flow_versions')
    op.drop_table_comment(
        'flow_versions',
        existing_comment='娴佺▼鐗堟湰',
        schema=None
    )
    op.alter_column('instance_edges', 'instance_id',
               existing_type=mysql.INTEGER(),
               comment='所属实例',
               existing_comment='鎵?睘瀹炰緥',
               existing_nullable=False)
    op.alter_column('instance_edges', 'source_node_id',
               existing_type=mysql.INTEGER(),
               comment='源节点',
               existing_comment='婧愯妭鐐',
               existing_nullable=False)
    op.alter_column('instance_edges', 'target_node_id',
               existing_type=mysql.INTEGER(),
               comment='目标节点',
               existing_comment='鐩?爣鑺傜偣',
               existing_nullable=False)
    op.drop_index('idx_instance', table_name='instance_edges')
    op.drop_index('idx_source', table_name='instance_edges')
    op.drop_index('idx_target', table_name='instance_edges')
    op.drop_table_comment(
        'instance_edges',
        existing_comment='瀹炰緥杩炵嚎',
        schema=None
    )
    op.alter_column('instance_nodes', 'instance_id',
               existing_type=mysql.INTEGER(),
               comment='所属实例',
               existing_comment='鎵?睘瀹炰緥',
               existing_nullable=False)
    op.alter_column('instance_nodes', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment='节点名称',
               existing_comment='鑺傜偣鍚嶇О',
               existing_nullable=False)
    op.alter_column('instance_nodes', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='节点描述',
               existing_comment='鑺傜偣鎻忚堪',
               existing_nullable=True)
    op.alter_column('instance_nodes', 'is_start',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment='是否开始节点',
               existing_comment='鏄?惁寮??鑺傜偣',
               existing_server_default=sa.text("'0'"))
    op.alter_column('instance_nodes', 'is_end',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment='是否结束节点',
               existing_comment='鏄?惁缁撴潫鑺傜偣',
               existing_server_default=sa.text("'0'"))
    op.alter_column('instance_nodes', 'assignee_id',
               existing_type=mysql.INTEGER(),
               comment='负责人',
               existing_comment='璐熻矗浜',
               existing_nullable=True)
    op.alter_column('instance_nodes', 'time_limit_days',
               existing_type=mysql.INTEGER(),
               comment='完成时限天数',
               existing_comment='瀹屾垚鏃堕檺澶╂暟',
               existing_nullable=True)
    op.alter_column('instance_nodes', 'deadline',
               existing_type=mysql.DATETIME(),
               comment='截止时间',
               existing_comment='鎴??鏃堕棿',
               existing_nullable=True)
    op.alter_column('instance_nodes', 'require_file',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment='是否必须上传文件',
               existing_comment='鏄?惁蹇呴』涓婁紶鏂囦欢',
               existing_server_default=sa.text("'0'"))
    op.alter_column('instance_nodes', 'approvers',
               existing_type=mysql.JSON(),
               comment='审批人列表',
               existing_comment='瀹℃壒浜哄垪琛',
               existing_nullable=True)
    op.alter_column('instance_nodes', 'checkers',
               existing_type=mysql.JSON(),
               comment='校验人列表',
               existing_comment='鏍￠獙浜哄垪琛',
               existing_nullable=True)
    op.alter_column('instance_nodes', 'approval_strategy',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               nullable=False,
               comment='审批策略',
               existing_comment='瀹℃壒绛栫暐',
               existing_server_default=sa.text("'all_approve'"))
    op.alter_column('instance_nodes', 'is_optional',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment='是否可选节点',
               existing_comment='鏄?惁鍙??鑺傜偣锛堝彂璧峰疄渚嬫椂鍙?兘琚?烦杩囷級',
               existing_server_default=sa.text("'0'"))
    op.alter_column('instance_nodes', 'is_skipped',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment='是否被跳过',
               existing_comment='鏄?惁琚?烦杩囷紙is_optional=1涓斿彂璧锋椂閫夋嫨璺宠繃锛',
               existing_server_default=sa.text("'0'"))
    op.alter_column('instance_nodes', 'status',
               existing_type=mysql.ENUM('waiting', 'running', 'waiting_check', 'waiting_approval', 'finished', 'rejected', 'terminated', 'skipped', collation='utf8mb4_unicode_ci'),
               nullable=False,
               comment='节点状态',
               existing_comment='鑺傜偣鐘舵?',
               existing_server_default=sa.text("'waiting'"))
    op.alter_column('instance_nodes', 'sort_order',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='排序序号',
               existing_comment='鎺掑簭搴忓彿',
               existing_server_default=sa.text("'0'"))
    op.alter_column('instance_nodes', 'incoming_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='汇合节点上游连线数',
               existing_comment='姹囧悎鑺傜偣涓婃父杩炵嚎鏁帮紙涓茶仈=1锛屾眹鍚堢偣>1锛',
               existing_server_default=sa.text("'0'"))
    op.alter_column('instance_nodes', 'arrived_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='已完成上游分支数',
               existing_comment='宸插畬鎴愪笂娓稿垎鏀?暟锛?=incoming_count鏃舵縺娲伙級',
               existing_server_default=sa.text("'0'"))
    op.alter_column('instance_nodes', 'round',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='执行轮次',
               existing_comment='杞??锛堥┏鍥為噸鏂拌繘鍏ユ椂+1锛',
               existing_server_default=sa.text("'1'"))
    op.alter_column('instance_nodes', 'started_at',
               existing_type=mysql.DATETIME(),
               comment='节点激活时间',
               existing_comment='鑺傜偣婵?椿鏃堕棿',
               existing_nullable=True)
    op.alter_column('instance_nodes', 'completed_at',
               existing_type=mysql.DATETIME(),
               comment='节点完成时间',
               existing_comment='鑺傜偣瀹屾垚鏃堕棿',
               existing_nullable=True)
    op.alter_column('instance_nodes', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('instance_nodes', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index('idx_assignee', table_name='instance_nodes')
    op.drop_index('idx_instance', table_name='instance_nodes')
    op.drop_index('idx_status_deadline', table_name='instance_nodes')
    op.drop_table_comment(
        'instance_nodes',
        existing_comment='瀹炰緥鑺傜偣锛堣繍琛屾椂鐘舵?锛',
        schema=None
    )
    op.alter_column('operation_logs', 'id',
               existing_type=mysql.INTEGER(),
               comment='自增ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('operation_logs', 'instance_id',
               existing_type=mysql.INTEGER(),
               comment='所属流程实例',
               existing_comment='鎵?睘娴佺▼瀹炰緥锛堥潪娴佺▼鎿嶄綔涓篘ULL锛',
               existing_nullable=True)
    op.alter_column('operation_logs', 'operator_type',
               existing_type=mysql.ENUM('user', 'system', collation='utf8mb4_unicode_ci'),
               nullable=False,
               comment='操作者类型',
               existing_comment='鎿嶄綔鑰呯被鍨',
               existing_server_default=sa.text("'user'"))
    op.alter_column('operation_logs', 'operator_id',
               existing_type=mysql.INTEGER(),
               comment='操作人；系统操作为NULL',
               existing_comment='鎿嶄綔浜猴紱绯荤粺鎿嶄綔涓篘ULL',
               existing_nullable=True)
    op.alter_column('operation_logs', 'triggered_by',
               existing_type=mysql.INTEGER(),
               comment='可选触发人',
               existing_comment='鍙??瑙﹀彂浜',
               existing_nullable=True)
    op.alter_column('operation_logs', 'node_id',
               existing_type=mysql.INTEGER(),
               comment='关联实例节点',
               existing_comment='鍏宠仈瀹炰緥鑺傜偣',
               existing_nullable=True)
    op.alter_column('operation_logs', 'operation_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='操作类型',
               existing_comment='鎿嶄綔绫诲瀷',
               existing_nullable=False)
    op.alter_column('operation_logs', 'round',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='所属轮次',
               existing_comment='鎵?睘杞??',
               existing_server_default=sa.text("'1'"))
    op.alter_column('operation_logs', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='自动生成的描述文本',
               existing_comment='鑷?姩鐢熸垚鐨勬弿杩版枃鏈',
               existing_nullable=False)
    op.alter_column('operation_logs', 'detail',
               existing_type=mysql.JSON(),
               comment='操作详情',
               existing_comment='鎿嶄綔璇︽儏',
               existing_nullable=True)
    op.alter_column('operation_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='操作时间（分区键）',
               existing_comment='鎿嶄綔鏃堕棿锛堝垎鍖洪敭锛',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_created', table_name='operation_logs')
    op.drop_index('idx_instance', table_name='operation_logs')
    op.drop_index('idx_instance_created', table_name='operation_logs')
    op.drop_index('idx_node_round', table_name='operation_logs')
    op.drop_index('idx_operator', table_name='operation_logs')
    op.drop_index('idx_type', table_name='operation_logs')
    op.drop_table_comment(
        'operation_logs',
        existing_comment='鎿嶄綔鏃ュ織锛堝彧鍐欎笉鍒狅紝鎸夊勾鍒嗗尯锛',
        schema=None
    )
    op.alter_column('organizations', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='组织名称',
               existing_comment='缁勭粐鍚嶇О',
               existing_nullable=False)
    op.alter_column('organizations', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='组织描述',
               existing_comment='缁勭粐鎻忚堪',
               existing_nullable=True)
    op.alter_column('organizations', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment='是否启用',
               existing_comment='鏄?惁鍚?敤',
               existing_server_default=sa.text("'1'"))
    op.alter_column('organizations', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('organizations', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_table_comment(
        'organizations',
        existing_comment='缁勭粐锛堟墍锛',
        schema=None
    )
    op.alter_column('roles', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='角色名称',
               existing_comment='瑙掕壊鍚嶇О',
               existing_nullable=False)
    op.alter_column('roles', 'code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment='角色标识',
               existing_comment='瑙掕壊鏍囪瘑',
               existing_nullable=False)
    op.alter_column('roles', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='角色描述',
               existing_comment='瑙掕壊鎻忚堪',
               existing_nullable=True)
    op.alter_column('roles', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_table_comment(
        'roles',
        existing_comment='瑙掕壊',
        schema=None
    )
    op.alter_column('system_configs', 'config_key',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='配置键',
               existing_comment='閰嶇疆閿',
               existing_nullable=False)
    op.alter_column('system_configs', 'config_value',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='配置值',
               existing_comment='閰嶇疆鍊',
               existing_nullable=False)
    op.alter_column('system_configs', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='配置说明',
               existing_comment='閰嶇疆璇存槑',
               existing_nullable=True)
    op.alter_column('system_configs', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_table_comment(
        'system_configs',
        existing_comment='绯荤粺閰嶇疆',
        schema=None
    )
    op.alter_column('tasks', 'instance_id',
               existing_type=mysql.INTEGER(),
               comment='所属流程实例',
               existing_comment='鎵?睘娴佺▼瀹炰緥',
               existing_nullable=False)
    op.alter_column('tasks', 'node_id',
               existing_type=mysql.INTEGER(),
               comment='所属节点',
               existing_comment='鎵?睘鑺傜偣',
               existing_nullable=False)
    op.alter_column('tasks', 'assignee_id',
               existing_type=mysql.INTEGER(),
               comment='负责人',
               existing_comment='璐熻矗浜',
               existing_nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=mysql.ENUM('pending', 'processing', 'waiting_check', 'waiting_approval', 'completed', 'rejected', 'terminated', collation='utf8mb4_unicode_ci'),
               nullable=False,
               comment='任务状态',
               existing_comment='浠诲姟鐘舵?',
               existing_server_default=sa.text("'pending'"))
    op.alter_column('tasks', 'assignee_note',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='负责人备注',
               existing_comment='璐熻矗浜哄?娉',
               existing_nullable=True)
    op.alter_column('tasks', 'submitted_at',
               existing_type=mysql.DATETIME(),
               comment='提交时间',
               existing_comment='鎻愪氦鏃堕棿',
               existing_nullable=True)
    op.alter_column('tasks', 'completed_at',
               existing_type=mysql.DATETIME(),
               comment='完成时间',
               existing_comment='瀹屾垚鏃堕棿',
               existing_nullable=True)
    op.alter_column('tasks', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tasks', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index('idx_assignee', table_name='tasks')
    op.drop_index('idx_assignee_status', table_name='tasks')
    op.drop_index('idx_instance', table_name='tasks')
    op.drop_index('idx_node', table_name='tasks')
    op.drop_table_comment(
        'tasks',
        existing_comment='浠诲姟',
        schema=None
    )
    op.alter_column('template_edges', 'template_id',
               existing_type=mysql.INTEGER(),
               comment='所属模板',
               existing_comment='鎵?睘妯℃澘',
               existing_nullable=False)
    op.alter_column('template_edges', 'source_node_id',
               existing_type=mysql.INTEGER(),
               comment='源节点',
               existing_comment='婧愯妭鐐',
               existing_nullable=False)
    op.alter_column('template_edges', 'target_node_id',
               existing_type=mysql.INTEGER(),
               comment='目标节点',
               existing_comment='鐩?爣鑺傜偣',
               existing_nullable=False)
    op.drop_index('idx_template', table_name='template_edges')
    op.drop_table_comment(
        'template_edges',
        existing_comment='妯℃澘杩炵嚎',
        schema=None
    )
    op.alter_column('template_nodes', 'template_id',
               existing_type=mysql.INTEGER(),
               comment='所属模板',
               existing_comment='鎵?睘妯℃澘',
               existing_nullable=False)
    op.alter_column('template_nodes', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment='节点名称',
               existing_comment='鑺傜偣鍚嶇О',
               existing_nullable=False)
    op.alter_column('template_nodes', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='节点描述',
               existing_comment='鑺傜偣鎻忚堪',
               existing_nullable=True)
    op.alter_column('template_nodes', 'is_start',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment='是否开始节点',
               existing_comment='鏄?惁寮??鑺傜偣',
               existing_server_default=sa.text("'0'"))
    op.alter_column('template_nodes', 'is_end',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment='是否结束节点',
               existing_comment='鏄?惁缁撴潫鑺傜偣',
               existing_server_default=sa.text("'0'"))
    op.alter_column('template_nodes', 'assignee_id',
               existing_type=mysql.INTEGER(),
               comment='负责人',
               existing_comment='璐熻矗浜猴紙寮??/缁撴潫鑺傜偣涓篘ULL锛',
               existing_nullable=True)
    op.alter_column('template_nodes', 'time_limit_days',
               existing_type=mysql.INTEGER(),
               comment='完成时限天数',
               existing_comment='瀹屾垚鏃堕檺澶╂暟',
               existing_nullable=True)
    op.alter_column('template_nodes', 'require_file',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment='是否必须上传文件',
               existing_comment='鏄?惁蹇呴』涓婁紶鏂囦欢',
               existing_server_default=sa.text("'0'"))
    op.alter_column('template_nodes', 'approvers',
               existing_type=mysql.JSON(),
               comment='审批人列表',
               existing_comment='瀹℃壒浜哄垪琛',
               existing_nullable=True)
    op.alter_column('template_nodes', 'checkers',
               existing_type=mysql.JSON(),
               comment='校验人列表',
               existing_comment='鏍￠獙浜哄垪琛',
               existing_nullable=True)
    op.alter_column('template_nodes', 'approval_strategy',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               nullable=False,
               comment='审批策略',
               existing_comment='瀹℃壒绛栫暐',
               existing_server_default=sa.text("'all_approve'"))
    op.alter_column('template_nodes', 'is_optional',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment='是否可选节点',
               existing_comment='鏄?惁鍙??鑺傜偣锛堝彂璧峰疄渚嬫椂鍙??鎷╄烦杩囷級',
               existing_server_default=sa.text("'0'"))
    op.alter_column('template_nodes', 'position_x',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False,
               comment='画布X坐标',
               existing_comment='鐢诲竷X鍧愭爣',
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('template_nodes', 'position_y',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False,
               comment='画布Y坐标',
               existing_comment='鐢诲竷Y鍧愭爣',
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('template_nodes', 'sort_order',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='排序序号',
               existing_comment='鎺掑簭搴忓彿',
               existing_server_default=sa.text("'0'"))
    op.alter_column('template_nodes', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('template_nodes', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index('idx_assignee', table_name='template_nodes')
    op.drop_index('idx_template', table_name='template_nodes')
    op.drop_table_comment(
        'template_nodes',
        existing_comment='妯℃澘鑺傜偣',
        schema=None
    )
    op.drop_constraint('user_roles_ibfk_2', 'user_roles', type_='foreignkey')
    op.drop_constraint('user_roles_ibfk_1', 'user_roles', type_='foreignkey')
    op.drop_table_comment(
        'user_roles',
        existing_comment='鐢ㄦ埛瑙掕壊鍏宠仈',
        schema=None
    )
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment='登录用户名',
               existing_comment='鐧诲綍鐢ㄦ埛鍚',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='加密密码',
               existing_comment='鍔犲瘑瀵嗙爜',
               existing_nullable=False)
    op.alter_column('users', 'real_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='真实姓名',
               existing_comment='鐪熷疄濮撳悕',
               existing_nullable=False)
    op.alter_column('users', 'organization_id',
               existing_type=mysql.INTEGER(),
               comment='所属组织',
               existing_comment='鎵?睘缁勭粐',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='邮箱',
               existing_comment='閭??',
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='手机号',
               existing_comment='鎵嬫満鍙',
               existing_nullable=True)
    op.alter_column('users', 'signature_image',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='签名图片路径',
               existing_comment='绛惧悕鍥剧墖璺?緞',
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment='是否启用',
               existing_comment='鏄?惁鍚?敤',
               existing_server_default=sa.text("'1'"))
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index('idx_org', table_name='users')
    op.drop_table_comment(
        'users',
        existing_comment='鐢ㄦ埛',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        '鐢ㄦ埛',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_org', 'users', ['organization_id'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='鏄?惁鍚?敤',
               existing_comment='是否启用',
               existing_server_default=sa.text("'1'"))
    op.alter_column('users', 'signature_image',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='绛惧悕鍥剧墖璺?緞',
               existing_comment='签名图片路径',
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='鎵嬫満鍙',
               existing_comment='手机号',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='閭??',
               existing_comment='邮箱',
               existing_nullable=True)
    op.alter_column('users', 'organization_id',
               existing_type=mysql.INTEGER(),
               comment='鎵?睘缁勭粐',
               existing_comment='所属组织',
               existing_nullable=False)
    op.alter_column('users', 'real_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='鐪熷疄濮撳悕',
               existing_comment='真实姓名',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='鍔犲瘑瀵嗙爜',
               existing_comment='加密密码',
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment='鐧诲綍鐢ㄦ埛鍚',
               existing_comment='登录用户名',
               existing_nullable=False)
    op.create_table_comment(
        'user_roles',
        '鐢ㄦ埛瑙掕壊鍏宠仈',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key('user_roles_ibfk_1', 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_roles_ibfk_2', 'user_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_table_comment(
        'template_nodes',
        '妯℃澘鑺傜偣',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_template', 'template_nodes', ['template_id'], unique=False)
    op.create_index('idx_assignee', 'template_nodes', ['assignee_id'], unique=False)
    op.alter_column('template_nodes', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('template_nodes', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('template_nodes', 'sort_order',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='鎺掑簭搴忓彿',
               existing_comment='排序序号',
               existing_server_default=sa.text("'0'"))
    op.alter_column('template_nodes', 'position_y',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               nullable=True,
               comment='鐢诲竷Y鍧愭爣',
               existing_comment='画布Y坐标',
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('template_nodes', 'position_x',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               nullable=True,
               comment='鐢诲竷X鍧愭爣',
               existing_comment='画布X坐标',
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('template_nodes', 'is_optional',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='鏄?惁鍙??鑺傜偣锛堝彂璧峰疄渚嬫椂鍙??鎷╄烦杩囷級',
               existing_comment='是否可选节点',
               existing_server_default=sa.text("'0'"))
    op.alter_column('template_nodes', 'approval_strategy',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               nullable=True,
               comment='瀹℃壒绛栫暐',
               existing_comment='审批策略',
               existing_server_default=sa.text("'all_approve'"))
    op.alter_column('template_nodes', 'checkers',
               existing_type=mysql.JSON(),
               comment='鏍￠獙浜哄垪琛',
               existing_comment='校验人列表',
               existing_nullable=True)
    op.alter_column('template_nodes', 'approvers',
               existing_type=mysql.JSON(),
               comment='瀹℃壒浜哄垪琛',
               existing_comment='审批人列表',
               existing_nullable=True)
    op.alter_column('template_nodes', 'require_file',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='鏄?惁蹇呴』涓婁紶鏂囦欢',
               existing_comment='是否必须上传文件',
               existing_server_default=sa.text("'0'"))
    op.alter_column('template_nodes', 'time_limit_days',
               existing_type=mysql.INTEGER(),
               comment='瀹屾垚鏃堕檺澶╂暟',
               existing_comment='完成时限天数',
               existing_nullable=True)
    op.alter_column('template_nodes', 'assignee_id',
               existing_type=mysql.INTEGER(),
               comment='璐熻矗浜猴紙寮??/缁撴潫鑺傜偣涓篘ULL锛',
               existing_comment='负责人',
               existing_nullable=True)
    op.alter_column('template_nodes', 'is_end',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='鏄?惁缁撴潫鑺傜偣',
               existing_comment='是否结束节点',
               existing_server_default=sa.text("'0'"))
    op.alter_column('template_nodes', 'is_start',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='鏄?惁寮??鑺傜偣',
               existing_comment='是否开始节点',
               existing_server_default=sa.text("'0'"))
    op.alter_column('template_nodes', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='鑺傜偣鎻忚堪',
               existing_comment='节点描述',
               existing_nullable=True)
    op.alter_column('template_nodes', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment='鑺傜偣鍚嶇О',
               existing_comment='节点名称',
               existing_nullable=False)
    op.alter_column('template_nodes', 'template_id',
               existing_type=mysql.INTEGER(),
               comment='鎵?睘妯℃澘',
               existing_comment='所属模板',
               existing_nullable=False)
    op.create_table_comment(
        'template_edges',
        '妯℃澘杩炵嚎',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_template', 'template_edges', ['template_id'], unique=False)
    op.alter_column('template_edges', 'target_node_id',
               existing_type=mysql.INTEGER(),
               comment='鐩?爣鑺傜偣',
               existing_comment='目标节点',
               existing_nullable=False)
    op.alter_column('template_edges', 'source_node_id',
               existing_type=mysql.INTEGER(),
               comment='婧愯妭鐐',
               existing_comment='源节点',
               existing_nullable=False)
    op.alter_column('template_edges', 'template_id',
               existing_type=mysql.INTEGER(),
               comment='鎵?睘妯℃澘',
               existing_comment='所属模板',
               existing_nullable=False)
    op.create_table_comment(
        'tasks',
        '浠诲姟',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_node', 'tasks', ['node_id'], unique=False)
    op.create_index('idx_instance', 'tasks', ['instance_id'], unique=False)
    op.create_index('idx_assignee_status', 'tasks', ['assignee_id', 'status'], unique=False)
    op.create_index('idx_assignee', 'tasks', ['assignee_id'], unique=False)
    op.alter_column('tasks', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('tasks', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tasks', 'completed_at',
               existing_type=mysql.DATETIME(),
               comment='瀹屾垚鏃堕棿',
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('tasks', 'submitted_at',
               existing_type=mysql.DATETIME(),
               comment='鎻愪氦鏃堕棿',
               existing_comment='提交时间',
               existing_nullable=True)
    op.alter_column('tasks', 'assignee_note',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='璐熻矗浜哄?娉',
               existing_comment='负责人备注',
               existing_nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=mysql.ENUM('pending', 'processing', 'waiting_check', 'waiting_approval', 'completed', 'rejected', 'terminated', collation='utf8mb4_unicode_ci'),
               nullable=True,
               comment='浠诲姟鐘舵?',
               existing_comment='任务状态',
               existing_server_default=sa.text("'pending'"))
    op.alter_column('tasks', 'assignee_id',
               existing_type=mysql.INTEGER(),
               comment='璐熻矗浜',
               existing_comment='负责人',
               existing_nullable=False)
    op.alter_column('tasks', 'node_id',
               existing_type=mysql.INTEGER(),
               comment='鎵?睘鑺傜偣',
               existing_comment='所属节点',
               existing_nullable=False)
    op.alter_column('tasks', 'instance_id',
               existing_type=mysql.INTEGER(),
               comment='鎵?睘娴佺▼瀹炰緥',
               existing_comment='所属流程实例',
               existing_nullable=False)
    op.create_table_comment(
        'system_configs',
        '绯荤粺閰嶇疆',
        existing_comment=None,
        schema=None
    )
    op.alter_column('system_configs', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('system_configs', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='閰嶇疆璇存槑',
               existing_comment='配置说明',
               existing_nullable=True)
    op.alter_column('system_configs', 'config_value',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='閰嶇疆鍊',
               existing_comment='配置值',
               existing_nullable=False)
    op.alter_column('system_configs', 'config_key',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='閰嶇疆閿',
               existing_comment='配置键',
               existing_nullable=False)
    op.create_table_comment(
        'roles',
        '瑙掕壊',
        existing_comment=None,
        schema=None
    )
    op.alter_column('roles', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('roles', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='瑙掕壊鎻忚堪',
               existing_comment='角色描述',
               existing_nullable=True)
    op.alter_column('roles', 'code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment='瑙掕壊鏍囪瘑',
               existing_comment='角色标识',
               existing_nullable=False)
    op.alter_column('roles', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='瑙掕壊鍚嶇О',
               existing_comment='角色名称',
               existing_nullable=False)
    op.create_table_comment(
        'organizations',
        '缁勭粐锛堟墍锛',
        existing_comment=None,
        schema=None
    )
    op.alter_column('organizations', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('organizations', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('organizations', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='鏄?惁鍚?敤',
               existing_comment='是否启用',
               existing_server_default=sa.text("'1'"))
    op.alter_column('organizations', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='缁勭粐鎻忚堪',
               existing_comment='组织描述',
               existing_nullable=True)
    op.alter_column('organizations', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='缁勭粐鍚嶇О',
               existing_comment='组织名称',
               existing_nullable=False)
    op.create_table_comment(
        'operation_logs',
        '鎿嶄綔鏃ュ織锛堝彧鍐欎笉鍒狅紝鎸夊勾鍒嗗尯锛',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_type', 'operation_logs', ['operation_type'], unique=False)
    op.create_index('idx_operator', 'operation_logs', ['operator_id'], unique=False)
    op.create_index('idx_node_round', 'operation_logs', ['node_id', 'round'], unique=False)
    op.create_index('idx_instance_created', 'operation_logs', ['instance_id', 'created_at'], unique=False)
    op.create_index('idx_instance', 'operation_logs', ['instance_id'], unique=False)
    op.create_index('idx_created', 'operation_logs', ['created_at'], unique=False)
    op.alter_column('operation_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='鎿嶄綔鏃堕棿锛堝垎鍖洪敭锛',
               existing_comment='操作时间（分区键）',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('operation_logs', 'detail',
               existing_type=mysql.JSON(),
               comment='鎿嶄綔璇︽儏',
               existing_comment='操作详情',
               existing_nullable=True)
    op.alter_column('operation_logs', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='鑷?姩鐢熸垚鐨勬弿杩版枃鏈',
               existing_comment='自动生成的描述文本',
               existing_nullable=False)
    op.alter_column('operation_logs', 'round',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='鎵?睘杞??',
               existing_comment='所属轮次',
               existing_server_default=sa.text("'1'"))
    op.alter_column('operation_logs', 'operation_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='鎿嶄綔绫诲瀷',
               existing_comment='操作类型',
               existing_nullable=False)
    op.alter_column('operation_logs', 'node_id',
               existing_type=mysql.INTEGER(),
               comment='鍏宠仈瀹炰緥鑺傜偣',
               existing_comment='关联实例节点',
               existing_nullable=True)
    op.alter_column('operation_logs', 'triggered_by',
               existing_type=mysql.INTEGER(),
               comment='鍙??瑙﹀彂浜',
               existing_comment='可选触发人',
               existing_nullable=True)
    op.alter_column('operation_logs', 'operator_id',
               existing_type=mysql.INTEGER(),
               comment='鎿嶄綔浜猴紱绯荤粺鎿嶄綔涓篘ULL',
               existing_comment='操作人；系统操作为NULL',
               existing_nullable=True)
    op.alter_column('operation_logs', 'operator_type',
               existing_type=mysql.ENUM('user', 'system', collation='utf8mb4_unicode_ci'),
               nullable=True,
               comment='鎿嶄綔鑰呯被鍨',
               existing_comment='操作者类型',
               existing_server_default=sa.text("'user'"))
    op.alter_column('operation_logs', 'instance_id',
               existing_type=mysql.INTEGER(),
               comment='鎵?睘娴佺▼瀹炰緥锛堥潪娴佺▼鎿嶄綔涓篘ULL锛',
               existing_comment='所属流程实例',
               existing_nullable=True)
    op.alter_column('operation_logs', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='自增ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'instance_nodes',
        '瀹炰緥鑺傜偣锛堣繍琛屾椂鐘舵?锛',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_status_deadline', 'instance_nodes', ['status', 'deadline'], unique=False)
    op.create_index('idx_instance', 'instance_nodes', ['instance_id'], unique=False)
    op.create_index('idx_assignee', 'instance_nodes', ['assignee_id'], unique=False)
    op.alter_column('instance_nodes', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('instance_nodes', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('instance_nodes', 'completed_at',
               existing_type=mysql.DATETIME(),
               comment='鑺傜偣瀹屾垚鏃堕棿',
               existing_comment='节点完成时间',
               existing_nullable=True)
    op.alter_column('instance_nodes', 'started_at',
               existing_type=mysql.DATETIME(),
               comment='鑺傜偣婵?椿鏃堕棿',
               existing_comment='节点激活时间',
               existing_nullable=True)
    op.alter_column('instance_nodes', 'round',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='杞??锛堥┏鍥為噸鏂拌繘鍏ユ椂+1锛',
               existing_comment='执行轮次',
               existing_server_default=sa.text("'1'"))
    op.alter_column('instance_nodes', 'arrived_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='宸插畬鎴愪笂娓稿垎鏀?暟锛?=incoming_count鏃舵縺娲伙級',
               existing_comment='已完成上游分支数',
               existing_server_default=sa.text("'0'"))
    op.alter_column('instance_nodes', 'incoming_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='姹囧悎鑺傜偣涓婃父杩炵嚎鏁帮紙涓茶仈=1锛屾眹鍚堢偣>1锛',
               existing_comment='汇合节点上游连线数',
               existing_server_default=sa.text("'0'"))
    op.alter_column('instance_nodes', 'sort_order',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='鎺掑簭搴忓彿',
               existing_comment='排序序号',
               existing_server_default=sa.text("'0'"))
    op.alter_column('instance_nodes', 'status',
               existing_type=mysql.ENUM('waiting', 'running', 'waiting_check', 'waiting_approval', 'finished', 'rejected', 'terminated', 'skipped', collation='utf8mb4_unicode_ci'),
               nullable=True,
               comment='鑺傜偣鐘舵?',
               existing_comment='节点状态',
               existing_server_default=sa.text("'waiting'"))
    op.alter_column('instance_nodes', 'is_skipped',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='鏄?惁琚?烦杩囷紙is_optional=1涓斿彂璧锋椂閫夋嫨璺宠繃锛',
               existing_comment='是否被跳过',
               existing_server_default=sa.text("'0'"))
    op.alter_column('instance_nodes', 'is_optional',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='鏄?惁鍙??鑺傜偣锛堝彂璧峰疄渚嬫椂鍙?兘琚?烦杩囷級',
               existing_comment='是否可选节点',
               existing_server_default=sa.text("'0'"))
    op.alter_column('instance_nodes', 'approval_strategy',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               nullable=True,
               comment='瀹℃壒绛栫暐',
               existing_comment='审批策略',
               existing_server_default=sa.text("'all_approve'"))
    op.alter_column('instance_nodes', 'checkers',
               existing_type=mysql.JSON(),
               comment='鏍￠獙浜哄垪琛',
               existing_comment='校验人列表',
               existing_nullable=True)
    op.alter_column('instance_nodes', 'approvers',
               existing_type=mysql.JSON(),
               comment='瀹℃壒浜哄垪琛',
               existing_comment='审批人列表',
               existing_nullable=True)
    op.alter_column('instance_nodes', 'require_file',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='鏄?惁蹇呴』涓婁紶鏂囦欢',
               existing_comment='是否必须上传文件',
               existing_server_default=sa.text("'0'"))
    op.alter_column('instance_nodes', 'deadline',
               existing_type=mysql.DATETIME(),
               comment='鎴??鏃堕棿',
               existing_comment='截止时间',
               existing_nullable=True)
    op.alter_column('instance_nodes', 'time_limit_days',
               existing_type=mysql.INTEGER(),
               comment='瀹屾垚鏃堕檺澶╂暟',
               existing_comment='完成时限天数',
               existing_nullable=True)
    op.alter_column('instance_nodes', 'assignee_id',
               existing_type=mysql.INTEGER(),
               comment='璐熻矗浜',
               existing_comment='负责人',
               existing_nullable=True)
    op.alter_column('instance_nodes', 'is_end',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='鏄?惁缁撴潫鑺傜偣',
               existing_comment='是否结束节点',
               existing_server_default=sa.text("'0'"))
    op.alter_column('instance_nodes', 'is_start',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='鏄?惁寮??鑺傜偣',
               existing_comment='是否开始节点',
               existing_server_default=sa.text("'0'"))
    op.alter_column('instance_nodes', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='鑺傜偣鎻忚堪',
               existing_comment='节点描述',
               existing_nullable=True)
    op.alter_column('instance_nodes', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment='鑺傜偣鍚嶇О',
               existing_comment='节点名称',
               existing_nullable=False)
    op.alter_column('instance_nodes', 'instance_id',
               existing_type=mysql.INTEGER(),
               comment='鎵?睘瀹炰緥',
               existing_comment='所属实例',
               existing_nullable=False)
    op.create_table_comment(
        'instance_edges',
        '瀹炰緥杩炵嚎',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_target', 'instance_edges', ['target_node_id'], unique=False)
    op.create_index('idx_source', 'instance_edges', ['source_node_id'], unique=False)
    op.create_index('idx_instance', 'instance_edges', ['instance_id'], unique=False)
    op.alter_column('instance_edges', 'target_node_id',
               existing_type=mysql.INTEGER(),
               comment='鐩?爣鑺傜偣',
               existing_comment='目标节点',
               existing_nullable=False)
    op.alter_column('instance_edges', 'source_node_id',
               existing_type=mysql.INTEGER(),
               comment='婧愯妭鐐',
               existing_comment='源节点',
               existing_nullable=False)
    op.alter_column('instance_edges', 'instance_id',
               existing_type=mysql.INTEGER(),
               comment='鎵?睘瀹炰緥',
               existing_comment='所属实例',
               existing_nullable=False)
    op.create_table_comment(
        'flow_versions',
        '娴佺▼鐗堟湰',
        existing_comment=None,
        schema=None
    )
    op.create_index('uk_template_version', 'flow_versions', ['template_id', 'version_number'], unique=True)
    op.create_index('idx_template', 'flow_versions', ['template_id'], unique=False)
    op.alter_column('flow_versions', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('flow_versions', 'soft_config_overrides',
               existing_type=mysql.JSON(),
               comment='鐗堟湰绾ц妭鐐硅蒋閰嶇疆瑕嗙洊灞',
               existing_comment='版本级节点软配置覆盖层',
               existing_nullable=True)
    op.alter_column('flow_versions', 'published_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment='鍙戝竷鏃堕棿',
               existing_comment='发布时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('flow_versions', 'published_by',
               existing_type=mysql.INTEGER(),
               comment='鍙戝竷浜',
               existing_comment='发布人',
               existing_nullable=False)
    op.alter_column('flow_versions', 'edges_snapshot',
               existing_type=mysql.JSON(),
               comment='杩炵嚎蹇?収',
               existing_comment='连线快照',
               existing_nullable=False)
    op.alter_column('flow_versions', 'nodes_snapshot',
               existing_type=mysql.JSON(),
               comment='鑺傜偣蹇?収',
               existing_comment='节点快照',
               existing_nullable=False)
    op.alter_column('flow_versions', 'status',
               existing_type=mysql.ENUM('published', 'disabled', collation='utf8mb4_unicode_ci'),
               nullable=True,
               comment='鐗堟湰鐘舵?',
               existing_comment='版本状态',
               existing_server_default=sa.text("'published'"))
    op.alter_column('flow_versions', 'version_number',
               existing_type=mysql.INTEGER(),
               comment='鐗堟湰鍙',
               existing_comment='版本号',
               existing_nullable=False)
    op.alter_column('flow_versions', 'template_id',
               existing_type=mysql.INTEGER(),
               comment='鎵?睘妯℃澘',
               existing_comment='所属模板',
               existing_nullable=False)
    op.create_table_comment(
        'flow_templates',
        '娴佺▼妯℃澘',
        existing_comment=None,
        schema=None
    )
    op.create_index('uk_org_name', 'flow_templates', ['organization_id', 'name'], unique=True)
    op.create_index('idx_org_status', 'flow_templates', ['organization_id', 'status'], unique=False)
    op.create_index('idx_org', 'flow_templates', ['organization_id'], unique=False)
    op.alter_column('flow_templates', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('flow_templates', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('flow_templates', 'created_by',
               existing_type=mysql.INTEGER(),
               comment='鍒涘缓浜',
               existing_comment='创建人',
               existing_nullable=False)
    op.alter_column('flow_templates', 'current_version',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='褰撳墠鏈?柊鐗堟湰鍙',
               existing_comment='当前最新版本号',
               existing_server_default=sa.text("'0'"))
    op.alter_column('flow_templates', 'status',
               existing_type=mysql.ENUM('draft', 'published', 'disabled', collation='utf8mb4_unicode_ci'),
               nullable=True,
               comment='妯℃澘鐘舵?',
               existing_comment='模板状态',
               existing_server_default=sa.text("'draft'"))
    op.alter_column('flow_templates', 'organization_id',
               existing_type=mysql.INTEGER(),
               comment='鎵?睘缁勭粐',
               existing_comment='所属组织',
               existing_nullable=False)
    op.alter_column('flow_templates', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='娴佺▼鎻忚堪',
               existing_comment='流程描述',
               existing_nullable=True)
    op.alter_column('flow_templates', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='娴佺▼鍚嶇О',
               existing_comment='流程名称',
               existing_nullable=False)
    op.create_table_comment(
        'flow_instances',
        '娴佺▼瀹炰緥',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_version', 'flow_instances', ['version_id'], unique=False)
    op.create_index('idx_template', 'flow_instances', ['template_id'], unique=False)
    op.create_index('idx_org', 'flow_instances', ['organization_id'], unique=False)
    op.create_index('idx_initiator_status', 'flow_instances', ['initiator_id', 'status'], unique=False)
    op.create_index('idx_initiator', 'flow_instances', ['initiator_id'], unique=False)
    op.alter_column('flow_instances', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('flow_instances', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('flow_instances', 'terminated_at',
               existing_type=mysql.DATETIME(),
               comment='缁堟?鏃堕棿',
               existing_comment='终止时间',
               existing_nullable=True)
    op.alter_column('flow_instances', 'archived_at',
               existing_type=mysql.DATETIME(),
               comment='褰掓。鏃堕棿',
               existing_comment='归档时间',
               existing_nullable=True)
    op.alter_column('flow_instances', 'completed_at',
               existing_type=mysql.DATETIME(),
               comment='瀹屾垚鏃堕棿',
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('flow_instances', 'initiated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment='鍙戣捣鏃堕棿',
               existing_comment='发起时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('flow_instances', 'termination_reason',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='缁堟?鍘熷洜',
               existing_comment='终止原因',
               existing_nullable=True)
    op.alter_column('flow_instances', 'archive_status',
               existing_type=mysql.ENUM('not_archived', 'archived', collation='utf8mb4_unicode_ci'),
               nullable=True,
               comment='褰掓。鐘舵?',
               existing_comment='归档状态',
               existing_server_default=sa.text("'not_archived'"))
    op.alter_column('flow_instances', 'status',
               existing_type=mysql.ENUM('created', 'running', 'completed', 'terminated', collation='utf8mb4_unicode_ci'),
               nullable=True,
               comment='涓荤姸鎬',
               existing_comment='主状态',
               existing_server_default=sa.text("'created'"))
    op.alter_column('flow_instances', 'priority',
               existing_type=mysql.ENUM('urgent', 'high', 'normal', 'low', collation='utf8mb4_unicode_ci'),
               nullable=True,
               comment='浼樺厛绾',
               existing_comment='优先级',
               existing_server_default=sa.text("'normal'"))
    op.alter_column('flow_instances', 'initiator_id',
               existing_type=mysql.INTEGER(),
               comment='鍙戣捣浜猴紙鎵?暱锛',
               existing_comment='发起人',
               existing_nullable=False)
    op.alter_column('flow_instances', 'organization_id',
               existing_type=mysql.INTEGER(),
               comment='鎵?睘缁勭粐',
               existing_comment='所属组织',
               existing_nullable=False)
    op.alter_column('flow_instances', 'version_id',
               existing_type=mysql.INTEGER(),
               comment='鍩轰簬鐨勭増鏈',
               existing_comment='基于的版本',
               existing_nullable=False)
    op.alter_column('flow_instances', 'template_id',
               existing_type=mysql.INTEGER(),
               comment='浣跨敤鐨勬ā鏉',
               existing_comment='使用的模板',
               existing_nullable=False)
    op.alter_column('flow_instances', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='琛ュ厖璇存槑',
               existing_comment='补充说明',
               existing_nullable=True)
    op.alter_column('flow_instances', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='娴佺▼瀹炰緥鍚嶇О',
               existing_comment='流程实例名称',
               existing_nullable=False)
    op.create_table_comment(
        'files',
        '鏂囦欢',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_uploader', 'files', ['uploader_id'], unique=False)
    op.create_index('idx_task', 'files', ['task_id'], unique=False)
    op.create_index('idx_node', 'files', ['node_id'], unique=False)
    op.create_index('idx_instance', 'files', ['instance_id'], unique=False)
    op.alter_column('files', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment='鏇存柊鏃堕棿',
               existing_comment='更新时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('files', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment='鍒涘缓鏃堕棿',
               existing_comment='创建时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('files', 'mime_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='鏈?粓鏂囦欢MIME绫诲瀷',
               existing_comment='最终文件MIME类型',
               existing_nullable=False,
               existing_server_default=sa.text("'application/pdf'"))
    op.alter_column('files', 'file_size',
               existing_type=mysql.BIGINT(),
               comment='鏈?粓PDF澶у皬锛堝瓧鑺傦級',
               existing_comment='最终PDF大小（字节）',
               existing_nullable=True)
    op.alter_column('files', 'file_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='鏈?粓PDF瀛樺偍鐩稿?璺?緞',
               existing_comment='最终PDF存储相对路径',
               existing_nullable=False)
    op.alter_column('files', 'stored_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='瀛樺偍鏂囦欢鍚嶏紙UUID锛',
               existing_comment='存储文件名（UUID）',
               existing_nullable=False)
    op.alter_column('files', 'original_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='鍘熷?鏂囦欢鍚',
               existing_comment='原始文件名',
               existing_nullable=False)
    op.alter_column('files', 'upload_type',
               existing_type=mysql.ENUM('normal', 'supplement', collation='utf8mb4_unicode_ci'),
               nullable=True,
               comment='涓婁紶绫诲瀷',
               existing_comment='上传类型',
               existing_server_default=sa.text("'normal'"))
    op.alter_column('files', 'uploader_id',
               existing_type=mysql.INTEGER(),
               comment='涓婁紶浜',
               existing_comment='上传人',
               existing_nullable=False)
    op.alter_column('files', 'round',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='鏂囦欢鎵?睘杞??',
               existing_comment='文件所属轮次',
               existing_server_default=sa.text("'1'"))
    op.alter_column('files', 'task_id',
               existing_type=mysql.INTEGER(),
               comment='鍏宠仈浠诲姟锛堣ˉ浜ゅ彲涓篘ULL锛',
               existing_comment='关联任务（补交可为NULL）',
               existing_nullable=True)
    op.alter_column('files', 'node_id',
               existing_type=mysql.INTEGER(),
               comment='涓婁紶鑺傜偣',
               existing_comment='上传节点',
               existing_nullable=True)
    op.alter_column('files', 'instance_id',
               existing_type=mysql.INTEGER(),
               comment='鎵?睘娴佺▼瀹炰緥',
               existing_comment='所属流程实例',
               existing_nullable=False)
    op.create_table_comment(
        'check_records',
        '鏍￠獙璁板綍',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_task', 'check_records', ['task_id'], unique=False)
    op.create_index('idx_node', 'check_records', ['node_id'], unique=False)
    op.create_index('idx_instance', 'check_records', ['instance_id'], unique=False)
    op.create_index('idx_checker_status', 'check_records', ['checker_id', 'status'], unique=False)
    op.create_index('idx_checker', 'check_records', ['checker_id'], unique=False)
    op.alter_column('check_records', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('check_records', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('check_records', 'decided_at',
               existing_type=mysql.DATETIME(),
               comment='鏍￠獙鍐冲畾鏃堕棿',
               existing_comment='校验决定时间',
               existing_nullable=True)
    op.alter_column('check_records', 'opinion',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='鏍￠獙鎰忚?',
               existing_comment='校验意见',
               existing_nullable=True)
    op.alter_column('check_records', 'status',
               existing_type=mysql.ENUM('pending', 'passed', 'returned', 'terminated', collation='utf8mb4_unicode_ci'),
               nullable=True,
               comment='鏍￠獙鐘舵?',
               existing_comment='校验状态',
               existing_server_default=sa.text("'pending'"))
    op.alter_column('check_records', 'checker_id',
               existing_type=mysql.INTEGER(),
               comment='鏍￠獙浜',
               existing_comment='校验人',
               existing_nullable=False)
    op.alter_column('check_records', 'task_id',
               existing_type=mysql.INTEGER(),
               comment='鍏宠仈鐨凾ask',
               existing_comment='关联Task',
               existing_nullable=False)
    op.alter_column('check_records', 'node_id',
               existing_type=mysql.INTEGER(),
               comment='鎵?睘鑺傜偣',
               existing_comment='所属节点',
               existing_nullable=False)
    op.alter_column('check_records', 'instance_id',
               existing_type=mysql.INTEGER(),
               comment='鎵?睘娴佺▼瀹炰緥',
               existing_comment='所属流程实例',
               existing_nullable=False)
    op.create_table_comment(
        'approvals',
        '瀹℃壒璁板綍',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_task', 'approvals', ['task_id'], unique=False)
    op.create_index('idx_node', 'approvals', ['node_id'], unique=False)
    op.create_index('idx_instance', 'approvals', ['instance_id'], unique=False)
    op.create_index('idx_approver_status', 'approvals', ['approver_id', 'status'], unique=False)
    op.create_index('idx_approver', 'approvals', ['approver_id'], unique=False)
    op.alter_column('approvals', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('approvals', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('approvals', 'decided_at',
               existing_type=mysql.DATETIME(),
               comment='瀹℃壒鍐冲畾鏃堕棿',
               existing_comment='审批决定时间',
               existing_nullable=True)
    op.alter_column('approvals', 'signature_applied',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='绛惧悕鏄?惁宸蹭笂PDF',
               existing_comment='签名是否已上PDF',
               existing_server_default=sa.text("'0'"))
    op.alter_column('approvals', 'reject_target_node_id',
               existing_type=mysql.INTEGER(),
               comment='浠呯粨鏉熻妭鐐圭粓瀹℃?椹冲洖鐩?爣锛涗腑闂村?鎵逛负NULL',
               existing_comment='仅结束节点终审总驳回目标',
               existing_nullable=True)
    op.alter_column('approvals', 'opinion',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='瀹℃壒鎰忚?',
               existing_comment='审批意见',
               existing_nullable=True)
    op.alter_column('approvals', 'status',
               existing_type=mysql.ENUM('pending', 'approved', 'rejected', 'terminated', collation='utf8mb4_unicode_ci'),
               nullable=True,
               comment='瀹℃壒鐘舵?',
               existing_comment='审批状态',
               existing_server_default=sa.text("'pending'"))
    op.alter_column('approvals', 'approver_id',
               existing_type=mysql.INTEGER(),
               comment='瀹℃壒浜',
               existing_comment='审批人',
               existing_nullable=False)
    op.alter_column('approvals', 'task_id',
               existing_type=mysql.INTEGER(),
               comment='鍏宠仈鐨凾ask锛堢粨鏉熻妭鐐逛负NULL锛',
               existing_comment='关联Task（结束节点为NULL）',
               existing_nullable=True)
    op.alter_column('approvals', 'node_id',
               existing_type=mysql.INTEGER(),
               comment='鎵?睘鑺傜偣',
               existing_comment='所属节点',
               existing_nullable=False)
    op.alter_column('approvals', 'instance_id',
               existing_type=mysql.INTEGER(),
               comment='鎵?睘娴佺▼瀹炰緥',
               existing_comment='所属流程实例',
               existing_nullable=False)
    # ### end Alembic commands ###
