"""fix_charset_comments

Repair all table/column Chinese comments from SQLAlchemy model definitions.

Revision ID: fix_comments_001
Revises: 6247827b186e
Create Date: 2026-07-24
"""
from typing import Sequence, Union
from alembic import op

revision: str = "fix_comments_001"
down_revision: Union[str, None] = "6247827b186e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # ===== Table comments =====
    op.execute("ALTER TABLE approvals COMMENT '审批记录'")
    op.execute("ALTER TABLE check_records COMMENT '校验记录'")
    op.execute("ALTER TABLE document_templates COMMENT '文件模板'")
    op.execute("ALTER TABLE endorsements COMMENT '批准记录'")
    op.execute("ALTER TABLE files COMMENT '文件'")
    op.execute("ALTER TABLE flow_instances COMMENT '流程实例'")
    op.execute("ALTER TABLE flow_templates COMMENT '流程模板'")
    op.execute("ALTER TABLE instance_edges COMMENT '实例连线'")
    op.execute("ALTER TABLE instance_nodes COMMENT '实例节点（运行时状态）'")
    op.execute("ALTER TABLE node_presets COMMENT '节点预设'")
    op.execute("ALTER TABLE notifications COMMENT '通知'")
    op.execute("ALTER TABLE operation_logs COMMENT '操作日志（只写不删，按年分区）'")
    op.execute("ALTER TABLE organizations COMMENT '组织（所）'")
    op.execute("ALTER TABLE roles COMMENT '角色'")
    op.execute("ALTER TABLE signatures COMMENT '签名记录'")
    op.execute("ALTER TABLE system_configs COMMENT '系统配置'")
    op.execute("ALTER TABLE tasks COMMENT '任务'")
    op.execute("ALTER TABLE template_document_links COMMENT '模板文件关联'")
    op.execute("ALTER TABLE template_edges COMMENT '模板连线'")
    op.execute("ALTER TABLE template_nodes COMMENT '模板节点'")
    op.execute("ALTER TABLE user_roles COMMENT '用户角色关联'")
    op.execute("ALTER TABLE users COMMENT '用户'")

    # ===== Column comments =====
    # approvals
    op.execute("ALTER TABLE approvals MODIFY COLUMN `instance_id` INTEGER NOT NULL COMMENT '所属项目'")
    op.execute("ALTER TABLE approvals MODIFY COLUMN `node_id` INTEGER NOT NULL COMMENT '所属节点'")
    op.execute("ALTER TABLE approvals MODIFY COLUMN `task_id` INTEGER NULL COMMENT '关联Task（结束节点为NULL）'")
    op.execute("ALTER TABLE approvals MODIFY COLUMN `approver_id` INTEGER NOT NULL COMMENT '审批人'")
    op.execute("ALTER TABLE approvals MODIFY COLUMN `status` VARCHAR(20) NOT NULL COMMENT '审批状态'")
    op.execute("ALTER TABLE approvals MODIFY COLUMN `opinion` VARCHAR(500) NULL COMMENT '审批意见'")
    op.execute("ALTER TABLE approvals MODIFY COLUMN `round` INTEGER NOT NULL COMMENT '节点轮次（第几轮审批）'")
    op.execute("ALTER TABLE approvals MODIFY COLUMN `reject_target_node_id` INTEGER NULL COMMENT '仅结束节点终审总驳回目标'")
    op.execute("ALTER TABLE approvals MODIFY COLUMN `signature_applied` BOOLEAN NOT NULL COMMENT '签名是否已上PDF'")
    op.execute("ALTER TABLE approvals MODIFY COLUMN `signature_x` FLOAT NULL COMMENT '审批人调整后的签名X坐标'")
    op.execute("ALTER TABLE approvals MODIFY COLUMN `signature_y` FLOAT NULL COMMENT '审批人调整后的签名Y坐标'")
    op.execute("ALTER TABLE approvals MODIFY COLUMN `signature_page` INTEGER NULL COMMENT '审批人选择的签名页码'")
    op.execute("ALTER TABLE approvals MODIFY COLUMN `decided_at` DATETIME NULL COMMENT '审批决定时间'")
    # check_records
    op.execute("ALTER TABLE check_records MODIFY COLUMN `instance_id` INTEGER NOT NULL COMMENT '所属项目'")
    op.execute("ALTER TABLE check_records MODIFY COLUMN `node_id` INTEGER NOT NULL COMMENT '所属节点'")
    op.execute("ALTER TABLE check_records MODIFY COLUMN `task_id` INTEGER NOT NULL COMMENT '关联Task'")
    op.execute("ALTER TABLE check_records MODIFY COLUMN `checker_id` INTEGER NOT NULL COMMENT '校验人'")
    op.execute("ALTER TABLE check_records MODIFY COLUMN `status` VARCHAR(20) NOT NULL COMMENT '校验状态'")
    op.execute("ALTER TABLE check_records MODIFY COLUMN `opinion` VARCHAR(500) NULL COMMENT '校验意见'")
    op.execute("ALTER TABLE check_records MODIFY COLUMN `round` INTEGER NOT NULL COMMENT '节点轮次（第几轮校验）'")
    op.execute("ALTER TABLE check_records MODIFY COLUMN `decided_at` DATETIME NULL COMMENT '校验决定时间'")
    # document_templates
    op.execute("ALTER TABLE document_templates MODIFY COLUMN `organization_id` INTEGER NOT NULL COMMENT '所属组织'")
    op.execute("ALTER TABLE document_templates MODIFY COLUMN `name` VARCHAR(100) NOT NULL COMMENT '模板名称（显示给用户）'")
    op.execute("ALTER TABLE document_templates MODIFY COLUMN `original_name` VARCHAR(200) NOT NULL COMMENT '原始文件名'")
    op.execute("ALTER TABLE document_templates MODIFY COLUMN `file_path` VARCHAR(500) NOT NULL COMMENT '文件存储路径（相对 STORAGE_ROOT）'")
    op.execute("ALTER TABLE document_templates MODIFY COLUMN `file_size` INTEGER NOT NULL COMMENT '文件大小（字节）'")
    op.execute("ALTER TABLE document_templates MODIFY COLUMN `file_type` VARCHAR(10) NOT NULL COMMENT '文件类型：docx / xlsx'")
    op.execute("ALTER TABLE document_templates MODIFY COLUMN `created_by` INTEGER NOT NULL COMMENT '上传人'")
    # endorsements
    op.execute("ALTER TABLE endorsements MODIFY COLUMN `instance_id` INTEGER NOT NULL COMMENT '所属项目'")
    op.execute("ALTER TABLE endorsements MODIFY COLUMN `node_id` INTEGER NOT NULL COMMENT '所属节点'")
    op.execute("ALTER TABLE endorsements MODIFY COLUMN `task_id` INTEGER NULL COMMENT '关联Task（结束节点为NULL）'")
    op.execute("ALTER TABLE endorsements MODIFY COLUMN `endorser_id` INTEGER NOT NULL COMMENT '批准人'")
    op.execute("ALTER TABLE endorsements MODIFY COLUMN `status` VARCHAR(20) NOT NULL COMMENT '批准状态'")
    op.execute("ALTER TABLE endorsements MODIFY COLUMN `opinion` VARCHAR(500) NULL COMMENT '批准意见'")
    op.execute("ALTER TABLE endorsements MODIFY COLUMN `round` INTEGER NOT NULL COMMENT '节点轮次（第几轮批准）'")
    op.execute("ALTER TABLE endorsements MODIFY COLUMN `signature_applied` BOOLEAN NOT NULL COMMENT '签名是否已上PDF'")
    op.execute("ALTER TABLE endorsements MODIFY COLUMN `signature_x` FLOAT NULL COMMENT '批准人调整后的签名X坐标'")
    op.execute("ALTER TABLE endorsements MODIFY COLUMN `signature_y` FLOAT NULL COMMENT '批准人调整后的签名Y坐标'")
    op.execute("ALTER TABLE endorsements MODIFY COLUMN `signature_page` INTEGER NULL COMMENT '批准人选择的签名页码'")
    op.execute("ALTER TABLE endorsements MODIFY COLUMN `decided_at` DATETIME NULL COMMENT '批准决定时间'")
    # files
    op.execute("ALTER TABLE files MODIFY COLUMN `instance_id` INTEGER NOT NULL COMMENT '所属项目'")
    op.execute("ALTER TABLE files MODIFY COLUMN `node_id` INTEGER NULL COMMENT '上传节点'")
    op.execute("ALTER TABLE files MODIFY COLUMN `task_id` INTEGER NULL COMMENT '关联任务（补交可为NULL）'")
    op.execute("ALTER TABLE files MODIFY COLUMN `round` INTEGER NOT NULL COMMENT '文件所属轮次'")
    op.execute("ALTER TABLE files MODIFY COLUMN `uploader_id` INTEGER NOT NULL COMMENT '上传人'")
    op.execute("ALTER TABLE files MODIFY COLUMN `upload_type` VARCHAR(20) NOT NULL COMMENT '上传类型'")
    op.execute("ALTER TABLE files MODIFY COLUMN `folder_name` VARCHAR(100) NULL COMMENT '所属文件夹名称'")
    op.execute("ALTER TABLE files MODIFY COLUMN `original_name` VARCHAR(255) NOT NULL COMMENT '原始文件名'")
    op.execute("ALTER TABLE files MODIFY COLUMN `stored_name` VARCHAR(255) NOT NULL COMMENT '存储文件名（UUID）'")
    op.execute("ALTER TABLE files MODIFY COLUMN `file_path` VARCHAR(500) NOT NULL COMMENT '最终PDF存储相对路径'")
    op.execute("ALTER TABLE files MODIFY COLUMN `file_size` BIGINT NULL COMMENT '最终PDF大小（字节）'")
    op.execute("ALTER TABLE files MODIFY COLUMN `mime_type` VARCHAR(100) NOT NULL COMMENT '最终文件MIME类型'")
    op.execute("ALTER TABLE files MODIFY COLUMN `created_at` DATETIME NOT NULL COMMENT '创建时间'")
    op.execute("ALTER TABLE files MODIFY COLUMN `updated_at` DATETIME NOT NULL COMMENT '更新时间'")
    # flow_instances
    op.execute("ALTER TABLE flow_instances MODIFY COLUMN `name` VARCHAR(100) NOT NULL COMMENT '项目名称'")
    op.execute("ALTER TABLE flow_instances MODIFY COLUMN `description` VARCHAR(500) NULL COMMENT '补充说明'")
    op.execute("ALTER TABLE flow_instances MODIFY COLUMN `template_id` INTEGER NOT NULL COMMENT '使用的模板ID（冗余，无外键）'")
    op.execute("ALTER TABLE flow_instances MODIFY COLUMN `template_name` VARCHAR(100) NOT NULL COMMENT '模板名称快照（创建时冗余存储）'")
    op.execute("ALTER TABLE flow_instances MODIFY COLUMN `template_type` VARCHAR(20) NOT NULL COMMENT '模板类型快照: project / proposal（用于存储分目录等）'")
    op.execute("ALTER TABLE flow_instances MODIFY COLUMN `organization_id` INTEGER NOT NULL COMMENT '所属组织'")
    op.execute("ALTER TABLE flow_instances MODIFY COLUMN `initiator_id` INTEGER NOT NULL COMMENT '发起人'")
    op.execute("ALTER TABLE flow_instances MODIFY COLUMN `priority` VARCHAR(20) NOT NULL COMMENT '优先级'")
    op.execute("ALTER TABLE flow_instances MODIFY COLUMN `difficulty` VARCHAR(20) NOT NULL COMMENT '难度等级: 1/2/3/4'")
    op.execute("ALTER TABLE flow_instances MODIFY COLUMN `contract_no` VARCHAR(100) NULL COMMENT '合同号'")
    op.execute("ALTER TABLE flow_instances MODIFY COLUMN `product_model` VARCHAR(100) NULL COMMENT '产品型号'")
    op.execute("ALTER TABLE flow_instances MODIFY COLUMN `sales_manager` VARCHAR(50) NULL COMMENT '销售经理'")
    op.execute("ALTER TABLE flow_instances MODIFY COLUMN `proposal_id` INTEGER NULL COMMENT '关联的方案ID（仅项目类型可用）'")
    op.execute("ALTER TABLE flow_instances MODIFY COLUMN `doc_template_ids` JSON NULL COMMENT '实例级文件模板 ID 列表（发起时可调整，为空则继承模板关联）'")
    op.execute("ALTER TABLE flow_instances MODIFY COLUMN `status` VARCHAR(20) NOT NULL COMMENT '主状态'")
    op.execute("ALTER TABLE flow_instances MODIFY COLUMN `termination_reason` VARCHAR(500) NULL COMMENT '终止原因'")
    op.execute("ALTER TABLE flow_instances MODIFY COLUMN `initiated_at` DATETIME NOT NULL COMMENT '发起时间'")
    op.execute("ALTER TABLE flow_instances MODIFY COLUMN `completed_at` DATETIME NULL COMMENT '完成时间'")
    op.execute("ALTER TABLE flow_instances MODIFY COLUMN `terminated_at` DATETIME NULL COMMENT '终止时间'")
    # flow_templates
    op.execute("ALTER TABLE flow_templates MODIFY COLUMN `name` VARCHAR(50) NOT NULL COMMENT '流程名称'")
    op.execute("ALTER TABLE flow_templates MODIFY COLUMN `description` VARCHAR(500) NULL COMMENT '流程描述'")
    op.execute("ALTER TABLE flow_templates MODIFY COLUMN `type` VARCHAR(20) NOT NULL COMMENT '模板类型：project / proposal'")
    op.execute("ALTER TABLE flow_templates MODIFY COLUMN `organization_id` INTEGER NOT NULL COMMENT '所属组织'")
    op.execute("ALTER TABLE flow_templates MODIFY COLUMN `created_by` INTEGER NOT NULL COMMENT '创建人'")
    # instance_edges
    op.execute("ALTER TABLE instance_edges MODIFY COLUMN `instance_id` INTEGER NOT NULL COMMENT '所属实例'")
    op.execute("ALTER TABLE instance_edges MODIFY COLUMN `source_node_id` INTEGER NOT NULL COMMENT '源节点'")
    op.execute("ALTER TABLE instance_edges MODIFY COLUMN `target_node_id` INTEGER NOT NULL COMMENT '目标节点'")
    # instance_nodes
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `instance_id` INTEGER NOT NULL COMMENT '所属实例'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `name` VARCHAR(30) NOT NULL COMMENT '节点名称'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `description` VARCHAR(500) NULL COMMENT '节点描述'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `is_start` BOOLEAN NOT NULL COMMENT '是否开始节点'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `is_end` BOOLEAN NOT NULL COMMENT '是否结束节点'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `assignee_id` INTEGER NULL COMMENT '负责人'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `time_limit_days` INTEGER NULL COMMENT '完成时限（工作日）'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `deadline` DATETIME NULL COMMENT '截止时间'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `require_file` BOOLEAN NOT NULL COMMENT '是否必须上传文件'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `file_folders` JSON NULL COMMENT '文件提交文件夹配置快照'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `approvers` JSON NULL COMMENT '审批人列表'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `checkers` JSON NULL COMMENT '校验人列表'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `approval_strategy` VARCHAR(30) NOT NULL COMMENT '审批策略'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `require_assignee_signature` BOOLEAN NOT NULL COMMENT '负责人提交时是否签名'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `require_checker_signature` BOOLEAN NOT NULL COMMENT '校验人通过时是否签名'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `require_approver_signature` BOOLEAN NOT NULL COMMENT '审批人通过时是否签名'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `endorser_id` INTEGER NULL COMMENT '批准人（单人）'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `require_endorser_signature` BOOLEAN NOT NULL COMMENT '批准人通过时是否签名'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `signature_x` FLOAT NOT NULL COMMENT '签名默认X坐标（距左边）'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `signature_y` FLOAT NOT NULL COMMENT '签名默认Y坐标（距底部）'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `signature_page` INTEGER NOT NULL COMMENT '签名默认页码（-1=最后一页）'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `status` VARCHAR(20) NOT NULL COMMENT '节点状态'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `sort_order` INTEGER NOT NULL COMMENT '排序序号'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `incoming_count` INTEGER NOT NULL COMMENT '汇合节点上游连线数'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `arrived_count` INTEGER NOT NULL COMMENT '已完成上游分支数'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `round` INTEGER NOT NULL COMMENT '执行轮次'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `started_at` DATETIME NULL COMMENT '节点激活时间'")
    op.execute("ALTER TABLE instance_nodes MODIFY COLUMN `completed_at` DATETIME NULL COMMENT '节点完成时间'")
    # node_presets
    op.execute("ALTER TABLE node_presets MODIFY COLUMN `user_id` INTEGER NOT NULL COMMENT '所属用户'")
    op.execute("ALTER TABLE node_presets MODIFY COLUMN `name` VARCHAR(30) NOT NULL COMMENT '预设名称（列表中显示）'")
    op.execute("ALTER TABLE node_presets MODIFY COLUMN `node_name` VARCHAR(30) NOT NULL COMMENT '拖出后默认节点名称'")
    op.execute("ALTER TABLE node_presets MODIFY COLUMN `assignee_id` INTEGER NULL COMMENT '负责人 ID'")
    op.execute("ALTER TABLE node_presets MODIFY COLUMN `checkers` JSON NULL COMMENT '校验人列表 [{\"user_id\": N}]'")
    op.execute("ALTER TABLE node_presets MODIFY COLUMN `approvers` JSON NULL COMMENT '审批人列表 [{\"user_id\": N}]'")
    op.execute("ALTER TABLE node_presets MODIFY COLUMN `time_limit_days` INTEGER NULL COMMENT '完成时限（工作日）'")
    op.execute("ALTER TABLE node_presets MODIFY COLUMN `require_file` BOOLEAN NOT NULL COMMENT '是否必须上传文件'")
    op.execute("ALTER TABLE node_presets MODIFY COLUMN `sort_order` INTEGER NOT NULL COMMENT '排序序号（预留拖拽排序）'")
    # notifications
    op.execute("ALTER TABLE notifications MODIFY COLUMN `user_id` INTEGER NOT NULL COMMENT '接收人'")
    op.execute("ALTER TABLE notifications MODIFY COLUMN `type` VARCHAR(30) NOT NULL COMMENT '通知类型: task_assigned/check_assigned/approval_assigned/endorsement_assigned/check_returned/approval_rejected/final_rejected/endorsement_rejected'")
    op.execute("ALTER TABLE notifications MODIFY COLUMN `title` VARCHAR(200) NOT NULL COMMENT '通知标题'")
    op.execute("ALTER TABLE notifications MODIFY COLUMN `content` VARCHAR(500) NOT NULL COMMENT '通知内容'")
    op.execute("ALTER TABLE notifications MODIFY COLUMN `link` VARCHAR(300) NULL COMMENT '点击跳转路径'")
    op.execute("ALTER TABLE notifications MODIFY COLUMN `is_read` BOOLEAN NOT NULL COMMENT '是否已读'")
    op.execute("ALTER TABLE notifications MODIFY COLUMN `created_at` DATETIME NOT NULL COMMENT '通知时间'")
    # operation_logs
    op.execute("ALTER TABLE operation_logs MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT COMMENT '自增ID'")
    op.execute("ALTER TABLE operation_logs MODIFY COLUMN `instance_id` INTEGER NULL COMMENT '所属项目'")
    op.execute("ALTER TABLE operation_logs MODIFY COLUMN `operator_type` VARCHAR(20) NOT NULL DEFAULT 'user' COMMENT '操作者类型'")
    op.execute("ALTER TABLE operation_logs MODIFY COLUMN `operator_id` INTEGER NULL COMMENT '操作人；系统操作为NULL'")
    op.execute("ALTER TABLE operation_logs MODIFY COLUMN `triggered_by` INTEGER NULL COMMENT '可选触发人'")
    op.execute("ALTER TABLE operation_logs MODIFY COLUMN `node_id` INTEGER NULL COMMENT '关联实例节点'")
    op.execute("ALTER TABLE operation_logs MODIFY COLUMN `operation_type` VARCHAR(50) NOT NULL COMMENT '操作类型'")
    op.execute("ALTER TABLE operation_logs MODIFY COLUMN `round` INTEGER NOT NULL DEFAULT 1 COMMENT '所属轮次'")
    op.execute("ALTER TABLE operation_logs MODIFY COLUMN `description` VARCHAR(500) NOT NULL COMMENT '自动生成的描述文本'")
    op.execute("ALTER TABLE operation_logs MODIFY COLUMN `detail` JSON NULL COMMENT '操作详情'")
    op.execute("ALTER TABLE operation_logs MODIFY COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间（分区键）'")
    # organizations
    op.execute("ALTER TABLE organizations MODIFY COLUMN `name` VARCHAR(50) NOT NULL COMMENT '组织名称'")
    op.execute("ALTER TABLE organizations MODIFY COLUMN `description` VARCHAR(500) NULL COMMENT '组织描述'")
    op.execute("ALTER TABLE organizations MODIFY COLUMN `is_active` BOOLEAN NOT NULL COMMENT '是否启用'")
    # roles
    op.execute("ALTER TABLE roles MODIFY COLUMN `name` VARCHAR(50) NOT NULL COMMENT '角色名称'")
    op.execute("ALTER TABLE roles MODIFY COLUMN `code` VARCHAR(30) NOT NULL COMMENT '角色标识'")
    op.execute("ALTER TABLE roles MODIFY COLUMN `description` VARCHAR(200) NULL COMMENT '角色描述'")
    # signatures
    op.execute("ALTER TABLE signatures MODIFY COLUMN `file_id` INTEGER NOT NULL COMMENT '签在哪个文件'")
    op.execute("ALTER TABLE signatures MODIFY COLUMN `signer_id` INTEGER NOT NULL COMMENT '签名人'")
    op.execute("ALTER TABLE signatures MODIFY COLUMN `role_type` VARCHAR(20) NOT NULL COMMENT '签名角色 assignee|checker|approver'")
    op.execute("ALTER TABLE signatures MODIFY COLUMN `source_id` INTEGER NOT NULL COMMENT '业务记录ID task_id/check_id/approval_id'")
    op.execute("ALTER TABLE signatures MODIFY COLUMN `node_id` INTEGER NOT NULL COMMENT '所属节点'")
    op.execute("ALTER TABLE signatures MODIFY COLUMN `signature_x` FLOAT NOT NULL COMMENT '签名X坐标（距左边）'")
    op.execute("ALTER TABLE signatures MODIFY COLUMN `signature_y` FLOAT NOT NULL COMMENT '签名Y坐标（距底部）'")
    op.execute("ALTER TABLE signatures MODIFY COLUMN `signature_page` INTEGER NOT NULL COMMENT '签名页码 -1=最后一页'")
    op.execute("ALTER TABLE signatures MODIFY COLUMN `signature_width` FLOAT NULL COMMENT '签名指定宽度（NULL=使用全局配置）'")
    op.execute("ALTER TABLE signatures MODIFY COLUMN `signature_height` FLOAT NULL COMMENT '签名指定高度（NULL=使用全局配置）'")
    op.execute("ALTER TABLE signatures MODIFY COLUMN `applied` BOOLEAN NOT NULL COMMENT '是否已写入PDF'")
    op.execute("ALTER TABLE signatures MODIFY COLUMN `sort_order` INTEGER NOT NULL COMMENT '同文件同角色多次签名排序'")
    # system_configs
    op.execute("ALTER TABLE system_configs MODIFY COLUMN `config_key` VARCHAR(100) NOT NULL COMMENT '配置键'")
    op.execute("ALTER TABLE system_configs MODIFY COLUMN `config_value` VARCHAR(500) NOT NULL COMMENT '配置值'")
    op.execute("ALTER TABLE system_configs MODIFY COLUMN `description` VARCHAR(200) NULL COMMENT '配置说明'")
    # tasks
    op.execute("ALTER TABLE tasks MODIFY COLUMN `instance_id` INTEGER NOT NULL COMMENT '所属项目'")
    op.execute("ALTER TABLE tasks MODIFY COLUMN `node_id` INTEGER NOT NULL COMMENT '所属节点'")
    op.execute("ALTER TABLE tasks MODIFY COLUMN `assignee_id` INTEGER NOT NULL COMMENT '负责人'")
    op.execute("ALTER TABLE tasks MODIFY COLUMN `status` VARCHAR(20) NOT NULL COMMENT '任务状态'")
    op.execute("ALTER TABLE tasks MODIFY COLUMN `assignee_note` VARCHAR(500) NULL COMMENT '负责人备注'")
    op.execute("ALTER TABLE tasks MODIFY COLUMN `submitted_at` DATETIME NULL COMMENT '提交时间'")
    op.execute("ALTER TABLE tasks MODIFY COLUMN `completed_at` DATETIME NULL COMMENT '完成时间'")
    # template_document_links
    op.execute("ALTER TABLE template_document_links MODIFY COLUMN `template_id` INTEGER NOT NULL COMMENT '流程模板 ID'")
    op.execute("ALTER TABLE template_document_links MODIFY COLUMN `document_id` INTEGER NOT NULL COMMENT '文件模板 ID'")
    # template_edges
    op.execute("ALTER TABLE template_edges MODIFY COLUMN `template_id` INTEGER NOT NULL COMMENT '所属模板'")
    op.execute("ALTER TABLE template_edges MODIFY COLUMN `source_node_id` INTEGER NOT NULL COMMENT '源节点'")
    op.execute("ALTER TABLE template_edges MODIFY COLUMN `target_node_id` INTEGER NOT NULL COMMENT '目标节点'")
    op.execute("ALTER TABLE template_edges MODIFY COLUMN `points` TEXT NULL COMMENT '折线路径点串（LogicFlow points 字符串，保存后恢复避免路由重算）'")
    # template_nodes
    op.execute("ALTER TABLE template_nodes MODIFY COLUMN `template_id` INTEGER NOT NULL COMMENT '所属模板'")
    op.execute("ALTER TABLE template_nodes MODIFY COLUMN `name` VARCHAR(30) NOT NULL COMMENT '节点名称'")
    op.execute("ALTER TABLE template_nodes MODIFY COLUMN `description` VARCHAR(500) NULL COMMENT '节点描述'")
    op.execute("ALTER TABLE template_nodes MODIFY COLUMN `is_start` BOOLEAN NOT NULL COMMENT '是否开始节点'")
    op.execute("ALTER TABLE template_nodes MODIFY COLUMN `is_end` BOOLEAN NOT NULL COMMENT '是否结束节点'")
    op.execute("ALTER TABLE template_nodes MODIFY COLUMN `assignee_id` INTEGER NULL COMMENT '负责人'")
    op.execute("ALTER TABLE template_nodes MODIFY COLUMN `time_limit_days` INTEGER NULL COMMENT '完成时限（工作日）'")
    op.execute("ALTER TABLE template_nodes MODIFY COLUMN `require_file` BOOLEAN NOT NULL COMMENT '是否必须上传文件'")
    op.execute("ALTER TABLE template_nodes MODIFY COLUMN `file_folders` JSON NULL COMMENT '文件提交文件夹配置 [{name, required, file_count}]'")
    op.execute("ALTER TABLE template_nodes MODIFY COLUMN `approvers` JSON NULL COMMENT '审批人列表'")
    op.execute("ALTER TABLE template_nodes MODIFY COLUMN `checkers` JSON NULL COMMENT '校验人列表'")
    op.execute("ALTER TABLE template_nodes MODIFY COLUMN `approval_strategy` VARCHAR(30) NOT NULL COMMENT '审批策略'")
    op.execute("ALTER TABLE template_nodes MODIFY COLUMN `require_assignee_signature` BOOLEAN NOT NULL COMMENT '负责人提交时是否签名'")
    op.execute("ALTER TABLE template_nodes MODIFY COLUMN `require_checker_signature` BOOLEAN NOT NULL COMMENT '校验人通过时是否签名'")
    op.execute("ALTER TABLE template_nodes MODIFY COLUMN `require_approver_signature` BOOLEAN NOT NULL COMMENT '审批人通过时是否签名'")
    op.execute("ALTER TABLE template_nodes MODIFY COLUMN `endorser_id` INTEGER NULL COMMENT '批准人（仅difficulty=4时生效，单人）'")
    op.execute("ALTER TABLE template_nodes MODIFY COLUMN `require_endorser_signature` BOOLEAN NOT NULL COMMENT '批准人通过时是否签名'")
    op.execute("ALTER TABLE template_nodes MODIFY COLUMN `signature_x` FLOAT NOT NULL COMMENT '签名默认X坐标（距左边）'")
    op.execute("ALTER TABLE template_nodes MODIFY COLUMN `signature_y` FLOAT NOT NULL COMMENT '签名默认Y坐标（距底部）'")
    op.execute("ALTER TABLE template_nodes MODIFY COLUMN `signature_page` INTEGER NOT NULL COMMENT '签名默认页码（-1=最后一页）'")
    op.execute("ALTER TABLE template_nodes MODIFY COLUMN `position_x` FLOAT NOT NULL COMMENT '画布X坐标'")
    op.execute("ALTER TABLE template_nodes MODIFY COLUMN `position_y` FLOAT NOT NULL COMMENT '画布Y坐标'")
    op.execute("ALTER TABLE template_nodes MODIFY COLUMN `sort_order` INTEGER NOT NULL COMMENT '排序序号'")
    # users
    op.execute("ALTER TABLE users MODIFY COLUMN `username` VARCHAR(30) NOT NULL COMMENT '登录用户名'")
    op.execute("ALTER TABLE users MODIFY COLUMN `password_hash` VARCHAR(255) NOT NULL COMMENT '加密密码'")
    op.execute("ALTER TABLE users MODIFY COLUMN `real_name` VARCHAR(20) NOT NULL COMMENT '真实姓名'")
    op.execute("ALTER TABLE users MODIFY COLUMN `organization_id` INTEGER NOT NULL COMMENT '所属组织'")
    op.execute("ALTER TABLE users MODIFY COLUMN `email` VARCHAR(100) NULL COMMENT '邮箱'")
    op.execute("ALTER TABLE users MODIFY COLUMN `phone` VARCHAR(20) NULL COMMENT '手机号'")
    op.execute("ALTER TABLE users MODIFY COLUMN `signature_image` VARCHAR(500) NULL COMMENT '签名图片路径'")
    op.execute("ALTER TABLE users MODIFY COLUMN `is_active` BOOLEAN NOT NULL COMMENT '是否启用'")


def downgrade() -> None:
    """No-op"""
    pass